baseurl                 = "https://www.vivekrrao.com/"
languageCode            = "en-us"
title                   = "Vivek's Blog"
theme                   = "hugo-phlat-theme"

[permalinks]
    post                = "/:year/:month/:slug/"
    page                = "/:slug/"

[taxonomies]
    tag                 = "tags"
    category            = "categories"

# The header menu will appear as an inline-list at the top right of the page
[[menu.header]]
    name                = "Home"
    weight              = 1
    url                 = "/"

[[menu.header]]
    name                = "Profile"
    weight              = 3
    url                 = "/about/"

# The footer menu will appear as an inline-list at the bottom left of the footer found at the bottom of the screen
[[menu.footer]]
    name                = "Site Terms"
    weight              = 1
    url                 = "/site-terms/"

[params]
    keywords            = ["default", "keywords", "if", "no", "front", "matter"]
    description         = "A description that will appear as a default if front matter does not exist"
    google_analytics    = "UA-XXXXX-YY"
    google_adsense      = "ca-pub-XXXXXX"
    disqus              = "shortname"
    google_webmaster    = ""
    bing_webmaster      = ""
    alexa               = ""
    favicon             = ""

# Social media icons and links that appear in the footer
[social]
    twitter             = "https://www.twitter.com/_vrao_"
    linkedin            = "https://www.linkedin.com/in/vivekr1"
    github              = "https://github.com/vivekrrao"
    googleplus          = ""
    youtube             = ""
    paypal              = ""
    instagram           = ""
    reddit              = ""
    email               = ""
    pinterest           = ""
    wordpress           = ""
